Fixed ec2api_tempest_plugin test discovery issue
* On running tempest run -l, the ec2api-tempest-plugin is giving
  ImportError: Start directory is not importable: '/tmp/.venv/
  lib/python2.7/ec2api_tempest_plugin'. It is fixed by fixing
  the test discovery path.

* Added lxml and tempest as a Requires for the plugin.

Change-Id: Ie64d0e96565980201143c0547c8b63513c883ea4